services:
  mongo:
    container_name: session_mongo
    image: mongo:5.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: session_mongo

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: session_api
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes: 
      - ./:/app
      - /app/node_modules
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_HOST: session_mongo
      DB_NAME: learnPassportjs
      DB_PORT: 27017
      PORT: 4000
      SESSION_SECRET: some secret


